BEGIN;
DROP POLICY IF EXISTS tenants_self ON tenants;
DROP POLICY IF EXISTS teams_tenant ON teams;
DROP POLICY IF EXISTS users_tenant ON users;
DROP POLICY IF EXISTS enrollment_tokens_tenant ON enrollment_tokens;
DROP POLICY IF EXISTS devices_tenant ON devices;
DROP POLICY IF EXISTS calls_scope ON calls;
DROP POLICY IF EXISTS media_scope ON media_segments;
DROP POLICY IF EXISTS transcripts_scope ON transcripts;
DROP POLICY IF EXISTS analyses_scope ON analyses;
DROP POLICY IF EXISTS ptps_scope ON ptps;
DROP POLICY IF EXISTS rule_sets_scope ON rule_sets;
DROP POLICY IF EXISTS prompt_templates_scope ON prompt_templates;
DROP POLICY IF EXISTS flags_scope ON flags;
DROP POLICY IF EXISTS coverage_tenant ON coverage_daily;
DROP POLICY IF EXISTS device_events_tenant ON device_events;
DROP POLICY IF EXISTS audit_tenant ON audit_log;
DROP FUNCTION IF EXISTS sentinel_call_visible(uuid);
DROP FUNCTION IF EXISTS sentinel_can_see_call(text, uuid, boolean);
DROP FUNCTION IF EXISTS sentinel_team();
DROP FUNCTION IF EXISTS sentinel_role();
DROP FUNCTION IF EXISTS sentinel_uid();
DROP FUNCTION IF EXISTS sentinel_tenant();
COMMIT;
